install.packages("Hyde")
library(Hyde)

# summary(DATASET)

net <- HydeNetwork(~ x)

plot(net)

# (see `vignette("Customizing_Network_Graphs", package = "Hyde")`) 

net


#*** Using setNode()
#*** There are multiple ways to specify the distribution of a node in the network

#----------------------------------------------------------------------------------------------------------
# 1) Root Nodes
#----------------------------------------------------------------------------------------------------------
#  1.1) Binary
#    1.1.1) setNode(HydeNetwork, x, nodeType="dbern", p=0.62)   (need logic?  0<=p<=1)
#    1.1.2) Using JAGS code (nodeType="dbern", params="pi=0.28;"..or whatever the correct syntax is)
#  1.2) Categorical
#    1.2.1) setNode(HydeNetwork, x, nodeType="dcat",  p=c(0.62,0.08))
#           (need logic? if(length(p)==(K-1)) 0<=sum(p)<=1 else if(length(p)==K) sum(p)==1...)
#    1.2.2) Using JAGS code into the params argument, i.e., nodeType="dcat", 
#           params="pi.wells[1] = .85; pi.wells[2] = .12; pi.wells[3] = .03"
#           need specifics as to how that string needs to be constructed - for instance, 
#           do you need to use the name "pi.wells"?
#  1.3) Normal
#    1.3.1) setNode(HydeNetwork, x, nodeType="dnorm", mu=5, sigma=1.4)
#    1.3.2) Using JAGS code
#  1.4 Uniform
#    1.4.1) setNode(HydeNetwork, x, nodeType="dunif", a=0, b=10)
#    1.4.2) Using JAGS code
#  1.5 Weibull
#    1.5.1) setNode(HydeNetwork, x, nodeType="dweib", nu=3, lambda=1.5)
#    1.5.2) Using JAGS code
#  1.6 -- 1.1x  [dgamma, dexp, dpois, dnegbin, etc...]


#----------------------------------------------------------------------------------------------------------
# 2) Nodes With or Without Parents -- Manually specifying regression equations
#    >>> Do we need error checking to ensure alignment between stated terms in regression equations and 
#        network structure (i.e., if X1 and X2 are in the regression equation, they need to be stored
#        as parents of Y in the HydeNetwork object)?
#----------------------------------------------------------------------------------------------------------
#  2.1) Nodes in the exponential family -- need regression equation + link function
#    2.1.1) Ordinary Least Squares
#    2.1.2) Lognormal 
#    2.1.3) Logistic Regression nodes ... I think JAGS has a logit() function that may be useful
#    2.1.4) Poisson Regression nodes 
#    2.1.5) Gamma regression
#  2.2) Categorical nodes -- list (?) of multinomial logistic regression equations -- this will be tricky.
#  2.3) Continuous nodes
#    2.3.1) Regression equation with Gaussian errors
#  2.4) Manual specification using JAGS code
#    2.4.1) Linear regression equation with cauchy errors
#    2.4.2) Mixture distributions (do this last!)
#      2.4.2.1) Zero-inflated poisson
#      2.4.2.2) Zero-inflated negative binomial

#----------------------------------------------------------------------------------------------------------
# 3) Nodes With or Without Parents -- Reading formula from existing model objects
#    >>> Do we need error checking to ensure alignment between stated terms in regression equations and 
#        network structure (i.e., if X1 and X2 are in the regression equation, they need to be stored
#        as parents of Y in the HydeNetwork object)?
#----------------------------------------------------------------------------------------------------------
#  3.1) Reading from lm objects
#  3.2) Reading from glm objects  - can we make this work for lognormal?
#  3.3) Reading from multinom objects
#  3.4) Reading from survreg objects (note the list component modelObject$dist that stores the type
#       of distribution used for the parametric survival regression model)


#----------------------------------------------------------------------------------------------------------
# 4) Learning Node Distributions from Training Data
#----------------------------------------------------------------------------------------------------------
#  4.1) Default behavior of HydeNetwork(.formula, data=trainingData)
#  4.2) Tutorial involving user-specified distributions for particular nodes and estimation of regression
#       equations from data -- one node may be survival (with censoring), one may be binary, one may be normal,
#       one may be Poisson, and the other may be categorical


